# Generated by Django 5.0.4 on 2024-04-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
